version: '3.3'

services:
  db:
      container_name: "cluster-postgres"
      image: postgres:latest
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=trabalho1
      volumes:
         - ./dataPostgres:/var/lib/postgresql/data
          # copy the sql script to create tables
         - ./app/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      ports:
        - "5432:5432"
      networks:
        - mynetwork

networks:
  mynetwork:


